project:
  type: book

book:
  title: "w0_book"
  author: "Norah Jones"
  date: "1/21/2025"
  chapters:
    - index.qmd
    - note_sea_corrections.qmd
    - note_reweighting.qmd
    - B64.qmd
    - statistical_investigation_B64.qmd
    - B32.qmd
    - C48.qmd
    - pion_B64.qmd
    - pion_C80.qmd
    - pion_D96.qmd
    - fit_deriv_fpi.qmd
    - fit_deriv_fpi_C80.qmd
    - fit_all_deriv.qmd
    - fit_all_deriv_w0.qmd
    - w0_scale_setting.qmd
    - params.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
# prefer-html: true

format:
  html:
    theme: cosmo
    html-math-method: katex
  # pdf:
  #  documentclass: scrreprt



